// <auto-generated />
using Ecommerce.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecommerce.Migrations
{
    [DbContext(typeof(DbEcommerce))]
    partial class DbEcommerceModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ecommerce.Models.Produto", b =>
                {
                    b.Property<int>("ProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProdutoId"));

                    b.Property<string>("Imagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProdutoId");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            ProdutoId = 1,
                            Imagem = "manga.jpg",
                            Nome = "Manga",
                            Preco = 7.50m
                        },
                        new
                        {
                            ProdutoId = 2,
                            Imagem = "banana.jpg",
                            Nome = "Banana",
                            Preco = 4.0m
                        },
                        new
                        {
                            ProdutoId = 3,
                            Imagem = "goiaba.jpg",
                            Nome = "Goiaba",
                            Preco = 12.0m
                        },
                        new
                        {
                            ProdutoId = 4,
                            Imagem = "granola.jpg",
                            Nome = "Granola",
                            Preco = 22.0m
                        },
                        new
                        {
                            ProdutoId = 5,
                            Imagem = "maca.jpg",
                            Nome = "Maçã",
                            Preco = 8.50m
                        },
                        new
                        {
                            ProdutoId = 6,
                            Imagem = "melancia.jpg",
                            Nome = "Melancia",
                            Preco = 15.0m
                        },
                        new
                        {
                            ProdutoId = 7,
                            Imagem = "uva.jpg",
                            Nome = "Uva",
                            Preco = 20.0m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
